### PR TITLE
WIP port to work with lervag/wiki.vim

### PR DESCRIPTION
**Pull request by edrex**
Implement #232.

I'm going to run this branch and update it when I find bugs for a few weeks before it will be ready for review.

## Issues

- [x] working with markdown ft
- [ ] working with wiki ft
- [ ] BUG: marking task done works, but is reactivated on save
- [ ] figure out syntax highlighting in markdown
- [ ] figure out syntax highlighting in wiki format

### CODE REVIEW

**Comment by tbabej** [comment]
Really curious as to how this is going to turn out! I'd love to support this in taskwiki.

**Comment by edrex** [comment]
I'm still using lervag/wiki.vim and Taskwarrior but I've had taskwiki disabled for awhile since updates caused a bunch of red text breakage that I haven't had a chance to look into. I'm going to close this FTM and reopen when/if I get back around to it. Anyone motivated FF to pick it up and work on it.

**Comment by edrex** [comment]
@felixschurk tbh I jumped to https://helix-editor.com/ 6mo ago, and I use it with https://github.com/artempyanykh/marksman (autodetected by helix if in path). Helix strives to provide good working defaults, and doesn't even have plugins yet, so I can just use it without messing about.

**Comment by edrex** [comment]
@felixschurk tbh I jumped to https://helix-editor.com/ 6mo ago, and I use it with https://github.com/artempyanykh/marksman (autodetected by helix if in path). Helix strives to provide good working defaults, and doesn't even have plugins yet, so I can just use it without messing about.

**Comment by edrex** [comment]
I'm working on a direnv/nix based portable environment for markdown wikis, lmk if interested.

**Comment by edrex** [comment]
I'm working on a direnv/nix based portable environment for markdown wikis, lmk if interested.

**Comment by felixschurk** [comment]
@edrex 
Thank you for the response I am currently good with the wiki.vim. 
I will have a look onto it.

**Pull request closed without merging**
