### PR TITLE
GitHub Actions, docker image caching, test matrix update

### PR DESCRIPTION
**Pull request by liskin**
This pull request brings three significant changes to tests:

* Switch from Travis CI to GitHub Actions: speeds tests up a bit as all builds run in parallel, not just 4 as in Travis. The switch very slightly degrades the integration with coveralls.is (missing links from coveralls to builds, possibly something else), but I expect this to be sorted within a few months/years. Most importantly, the switch makes it possible to use GitHub Packages as a docker registry to cache the docker images.

* Docker image caching: instead of building the container again and again on every CI test run, the images are pushed to/pulled from GitHub Packages docker registry. This speeds up the image preparation from several minutes to less than 10 seconds.

* Test matrix update: test against different versions of vim, vimwiki and python in addition to different versions of taskwarrior. Now that the number of parallel builds isn't limited to 4 (thanks to GitHub Actions) and the docker build is cached (so we can afford to build vim from source), it's feasible to add more configurations to the test matrix.

Testing the updated matrix on Travis would taka cca 20-30 minutes (11 configurations = 3 batches of up to 4 jobs, each batch taking 6-7 minutes with the original Dockerfile that only built taskwarrior, so maybe up to 10 now), testing the old taskwarrior-only matrix took 13 minutes, GitHub Actions does it all under 4 minutes now. :racehorse: 

I do have to admit that my motivation to do this was not only to speed up the tests and cover more diverse environments, but also to experiment with GitHub Actions for the first time, so there may be some problems that I'm not yet aware of. But all in all it looks quite usable and fast. I'd love to hear what the others think!

### CODE REVIEW

**Comment by liskin** [comment]
To see it in action: https://github.com/liskin/taskwiki/actions

**Comment by liskin** [comment]
I was afraid that it might not work in a pull request so I tested it:
https://github.com/liskin/taskwiki/pull/1
https://github.com/liskin/taskwiki/actions/runs/179909866
It's still fast, coveralls apparently works as well, it just doesn't have the permission to push docker images into cache (which is expected) so if the Dockerfile changes in the PR, subsequent runs will be slow.

**Comment by tbabej** [comment]
Thanks for the great work. I agree with the concerns about the cache layers, but I'd say it's a limitation that we can live with.

**Comment by liskin** [comment]
Yeah, it's not a big limitation anyway: the action will actually run twice, once on the branch being pushed to the fork, and then again for the PR. The branch runs in the fork will be fast, so the person doing the development will have quick feedback from GitHub. Just the PR will take twice as long to update.

**Pull request merged**
