### PR TITLE
Fix incorrectly indented break

### PR DESCRIPTION
**Pull request by xyank-github**

### CODE REVIEW

**Comment by liskin** [comment]
A test demonstrating the effect of the misplaced `break` would be most welcome, too. :-)

**Comment by xyank-github** [comment]
git blame via `:Gblame` for that particular line returns this:

```diff
@@ -368,15 +376,20 @@ class VimwikiTask(object):
                 self.task.backend = port.tw
 
                 # Any defaults specified should be inherited
-                if port.defaults:
-                    for key in port.defaults.keys():
-                        self[key] = port.defaults[key]
+                self.update(port.defaults)
 
                 # If port was detected, break the search
-                break
 
-            # If line matches any header that is not a viewport,
-            # break the search too
-            line = self.cache.buffer[i]
-            if re.match(regexp.GENERIC_HEADER, line):
-                break
+            break
+
```

This isn't as good as a test, of course, but I have to be honest, while I can write a test for #289, I won't be able to write one for this without help.

**Comment by liskin** [comment]
I'll try to help you then :-)

**Comment by liskin** [comment]
Turns out the code is probably correct, just the comment is wrong. With your patch:

```
=============================================================== FAILURES ===============================================================
______________________________________________ TestPresetHierarchy.test_execute[default] _______________________________________________
>       assert task['tags'] == set(['work', 'easy'])
E       AssertionError: assert {'work', 'hard', 'easy'} == {'work', 'easy'}
E         Extra items in the left set:
E         'hard'
E         Full diff:
E         - {'work', 'easy'}
E         + {'work', 'hard', 'easy'}
E         ?          ++++++++

tests/test_preset.py:49: AssertionError

____________________________________________ TestPresetIgnoreViewport.test_execute[default] ____________________________________________
>       assert task['tags'] == set(['hard'])
E       AssertionError: assert {'work', 'hard'} == {'hard'}
E         Extra items in the left set:
E         'work'
E         Full diff:
E         - {'hard'}
E         + {'work', 'hard'}

tests/test_preset.py:143: AssertionError

_____________________________________ TestViewportDefaultsTerminatedByHeader.test_execute[default] _____________________________________
>       return self._result_cache.__getitem__(k)
E       IndexError: list index out of range

/usr/local/lib/python3.8/site-packages/tasklib/task.py:491: IndexError
```

(plus a couple more for markdown)

**Comment by liskin** [comment]
How about this instead: https://github.com/tools-life/taskwiki/pull/290 ?

**Comment by xyank-github** [comment]
This is much more clear than the previous code. I'd appreciate it if this is merged into master.

**Comment by liskin** [comment]
Let's close this one then?

**Pull request closed without merging**
